C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2_5972)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywraphw1 (hw1f2pywrap, a, b)
      external hw1
      real a
      real b
      real hw1f2pywrap, hw1
      hw1f2pywrap = hw1(a, b)
      end

